version: 2.1

jobs:
   tests:
      docker:
         - image: nastard/tests_f1department:latest
      steps:
         - checkout
         - run: make test

workflows:
   tests-workflow:
      jobs:
         - tests
